#include "App.h"

const T_parmenu parmenu[4]=
{
  {U3HB01_0,U3HB01_0,"Root","", -1},//  Корень
  {U3HB01_0,U3HB01_main,"Parameters and settings","PARAMETERS", -1},//  Основная категория
  {U3HB01_main,U3HB01_General,"General settings","GENERAL SETTINGS", -1},//  
  {U3HB01_main,U3HB01_Rotation,"Rotation task","ROTTASK", 0},//  
};


const T_work_params dwvar[13]=
{
  {
    " Device task ( 1-Solenoid, 2-Rotation) ",
    "DEVTASK",
    (void*)&wvar.dev_task,
    tint8u,
    1,
    1,
    2,
    0,
    U3HB01_General,
    "",
    "%d",
    0,
    sizeof(wvar.dev_task),
  },
  {
    " Firmware version ",
    "FRMVER",
    (void*)&wvar.ver,
    tstring,
    0,
    0,
    0,
    0,
    U3HB01_General,
    "?",
    "%s",
    0,
    sizeof(wvar.ver),
  },
  {
    " Product  name ",
    "SYSNAM",
    (void*)&wvar.name,
    tstring,
    0,
    0,
    0,
    0,
    U3HB01_General,
    "MDC 1.0",
    "%s",
    0,
    sizeof(wvar.name),
  },
  {
    " Enable LED strip control ",
    "SPENLST",
    (void*)&wvar.led_strip_en,
    tint8u,
    0,
    0,
    1,
    0,
    U3HB01_General,
    "",
    "%d",
    0,
    sizeof(wvar.led_strip_en),
  },
  {
    " Enable log to file ",
    "ENBLLOG",
    (void*)&wvar.en_log_file,
    tint8u,
    1,
    0,
    1,
    0,
    U3HB01_General,
    "",
    "%d",
    0,
    sizeof(wvar.en_log_file),
  },
  {
    " Enable verbose log ",
    "VERBLOG",
    (void*)&wvar.en_verbose_log,
    tint8u,
    0,
    0,
    1,
    0,
    U3HB01_General,
    "",
    "%d",
    0,
    sizeof(wvar.en_verbose_log),
  },
  {
    " PWM level (0..100%) ",
    "RPWMLEV",
    (void*)&wvar.rot_pwm_lev,
    tint8u,
    25,
    0,
    100,
    0,
    U3HB01_Rotation,
    "",
    "%d",
    0,
    sizeof(wvar.rot_pwm_lev),
  },
  {
    " Rotation direction (0-CW, 1-CCW) ",
    "RROTDIR",
    (void*)&wvar.rot_dir,
    tint8u,
    0,
    0,
    1,
    0,
    U3HB01_Rotation,
    "",
    "%d ",
    0,
    sizeof(wvar.rot_dir),
  },
  {
    " Force break PWM level(0..100%) ",
    "RFBRPLE",
    (void*)&wvar.rot_fbreak_pwm_lev,
    tint8u,
    5,
    0,
    100,
    0,
    U3HB01_Rotation,
    "",
    "%d",
    0,
    sizeof(wvar.rot_fbreak_pwm_lev),
  },
  {
    " Rotation step (pulse count) ",
    "ROTSTEP",
    (void*)&wvar.rot_steps,
    tint32u,
    0,
    0,
    1000000,
    0,
    U3HB01_Rotation,
    "",
    "%d",
    0,
    sizeof(wvar.rot_steps),
  },
  {
    " Enable speed filter ",
    "SPENSFL",
    (void*)&wvar.en_speed_fltr,
    tint8u,
    1,
    0,
    1,
    0,
    U3HB01_Spec,
    "",
    "%d",
    0,
    sizeof(wvar.en_speed_fltr),
  },
  {
    " Max current (A, rms) ",
    "SPMACCR",
    (void*)&wvar.max_curr,
    tfloat,
    10,
    0,
    100,
    0,
    U3HB01_Spec,
    "",
    "%0.1f",
    0,
    sizeof(wvar.max_curr),
  },
  {
    " Max long current (A, rms) ",
    "SPMLCUR",
    (void*)&wvar.max_long_curr,
    tfloat,
    3,
    0,
    100,
    0,
    U3HB01_Spec,
    "",
    "%0.1f",
    0,
    sizeof(wvar.max_long_curr),
  },
};
